### ISSUE TITLE
冒昧咨询下，这个方案和laravel-s有什么不同点呢

### ISSUE THREAD

**Issue by imdao** [huang-yi/shadowfax#13]
shadowfax和laravel-s，我都部署调试成功了，但是不知道还有什么区别，比如功能上，原理上，运行细节上，可否指点一下

**Comment by huang-yi** [comment]
抱歉，我对其它同类型的包了解并不深。

对于Shadowfax来说，它的目的是：让开发者以最小的成本，使其web应用获得性能提升。
（至于原理，以后有时间我可以写篇文章阐述一下）

可能有很多人对于结合Swoole和Laravel的理解是，赋予Laravel使用Swoole的能力，但Shadowfax只是为了让Laravel运行在Swoole之上，主要目的是提升性能，并不会去破坏Laravel的开发体验。Laravel它本身就是一个传统PHP模式下的框架，对Swoole并不友好，所以我不认同赋予Laravel使用Swoole的能力是一件合理的事情。

就我个人而言，我不会在我的Laravel应用里面使用Swoole的任何接口。一旦运行在Swoole上面的应用出了问题，我能够立马切回PHP-FPM模式，保证可用性。

**Comment by imdao** [comment]
好的，非常感谢您的回复和指教

**Comment by akirarika** [comment]
> 抱歉，我对其它同类型的包了解并不深。
> 
> 对于Shadowfax来说，它的目的是：让开发者以最小的成本，使其web应用获得性能提升。
> （至于原理，以后有时间我可以写篇文章阐述一下）
> 
> 可能有很多人对于结合Swoole和Laravel的理解是，赋予Laravel使用Swoole的能力，但Shadowfax只是为了让Laravel运行在Swoole之上，主要目的是提升性能，并不会去破坏Laravel的开发体验。Laravel它本身就是一个传统PHP模式下的框架，对Swoole并不友好，所以我不认同赋予Laravel使用Swoole的能力是一件合理的事情。
> 
> 就我个人而言，我不会在我的Laravel应用里面使用Swoole的任何接口。一旦运行在Swoole上面的应用出了问题，我能够立马切回PHP-FPM模式，保证可用性。

@huang-yi 您好，请问下，我这样理解您制作的扩展包是否正确呀：

swoole 和 php-fpm 最大的差别在于其生命周期，`laravel-swoole` 与 `laravel-s`  等包的目的是为 laravel 扩展 swoole 功能，同时因为常驻内存的生命周期为 laravel 带来了一些负面影响。

如单例对象会在下一个请求中保留上次请求的状态，导致被“污染”，他们的解决方案是手动配置一系列的清理器，在每次请求结束后重置这些对象的状态，同时也导致了许多原本运行在 php-fpm 下没有问题的插件在 swoole 中出现问题，需要手动兼容。

然后也导致 Laravel 的 `dd` 等函数无法使用，因为 `dd` 中会执行 `exit()`，导致整个 swoole 程序退出，而不是停止此次请求继续执行。

而 `shadowfax` 旨在尽可能利用 swoole 提升性能的同时，为 laravel 兼容原 php-fpm 的生命周期，避免上面所说的影响？

不知道我这样理解是否正确（

**Comment by huang-yi** [comment]
@imdao @akirarika 我写了一篇关于[Shadowfax是如何整合Laravel与Swoole](https://huangyi.tech/posts/how-did-shadowfax-integrate-laravel-with-swoole)的文章，希望可以帮助到。
