### ISSUE TITLE
php shadowfax start 启动报错

### ISSUE THREAD

**Issue by wenber-yu** [huang-yi/shadowfax#14]
php version: 7.4.7
os: macbook pro 10.15.5 (19F101)

[2020-06-17 16:59:16 *93899.7]	ERROR	php_swoole_server_rshutdown (ERRNO 503): Fatal error: Uncaught ErrorException: array_key_exists() expects parameter 2 to be array, null given in /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php:151
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'array_key_exist...', '/Users/wenber/h...', 151, Array)
#1 /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php(151): array_key_exists('client', NULL)
#2 /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php(249): Illuminate\Support\Arr::exists(NULL, 'client')
#3 /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php(487): Illuminate\Support\Arr::forget(NULL, Array)
#4 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Listeners/FrameworkBootstrappedEvent/OverrideRedisManager.php(26): Illuminate\Support\Arr::pull(NULL, 'client', 'phpredis')
#5 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/ in /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 151
    147|         if ($array instanceof ArrayAccess) {
    148|             return $array->offsetExists($key);
    149|         }
    150|
  > 151|         return array_key_exists($key, $array);
    152|     }
    153|
    154|     /**
    155|      * Return the first element in an array passing a given truth test.
    147|         if ($array instanceof ArrayAccess) {
    148|             return $array->offsetExists($key);
    149|         }
    150|
  > 151|         return array_key_exists($key, $array);
    152|     }
    153|
    154|     /**
    155|      * Return the first element in an array passing a given truth test.

      +1 vendor frames

      +1 vendor frames
  2   [internal]:0
      Whoops\Run::handleShutdown()
  2   [internal]:0
      Whoops\Run::handleShutdown()
[2020-06-17 16:59:16 *93904.4]	ERROR	php_swoole_server_rshutdown (ERRNO 503): Fatal error: Uncaught ErrorException: array_key_exists() expects parameter 2 to be array, null given in /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php:151
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'array_key_exist...', '/Users/wenber/h...', 151, Array)
#1 /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php(151): array_key_exists('client', NULL)
#2 /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php(249): Illuminate\Support\Arr::exists(NULL, 'client')
#3 /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php(487): Illuminate\Support\Arr::forget(NULL, Array)
#4 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Listeners/FrameworkBootstrappedEvent/OverrideRedisManager.php(26): Illuminate\Support\Arr::pull(NULL, 'client', 'phpredis')
#5 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/ in /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 151
[2020-06-17 16:59:16 *93903.2]	ERROR	php_swoole_server_rshutdown (ERRNO 503): Fatal error: Uncaught ErrorException: array_key_exists() expects parameter 2 to be array, null given in /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php:151
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'array_key_exist...', '/Users/wenber/h...', 151, Array)
#1 /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php(151): array_key_exists('client', NULL)
#2 /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php(249): Illuminate\Support\Arr::exists(NULL, 'client')
#3 /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php(487): Illuminate\Support\Arr::forget(NULL, Array)
#4 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Listeners/FrameworkBootstrappedEvent/OverrideRedisManager.php(26): Illuminate\Support\Arr::pull(NULL, 'client', 'phpredis')
#5 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/ in /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 151

   Whoops\Exception\ErrorException

  Uncaught ErrorException: array_key_exists() expects parameter 2 to be array, null given in /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php:151
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'array_key_exist...', '/Users/wenber/h...', 151, Array)
#1 /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php(151): array_key_exists('client', NULL)
#2 /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php(249): Illuminate\Support\Arr::exists(NULL, 'client')
#3 /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php(487): Illuminate\Support\Arr::forget(NULL, Array)
#4 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Listeners/FrameworkBootstrappedEvent/OverrideRedisManager.php(26): Illuminate\Support\Arr::pull(NULL, 'client', 'phpredis')
#5 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/

  at vendor/laravel/framework/src/Illuminate/Support/Arr.php:151
    147|         if ($array instanceof ArrayAccess) {
    148|             return $array->offsetExists($key);
    149|         }
    150|
  > 151|         return array_key_exists($key, $array);
    152|     }
    153|
    154|     /**
    155|      * Return the first element in an array passing a given truth test.
PHP Fatal error:  Uncaught ErrorException: array_key_exists() expects parameter 2 to be array, null given in /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php:151
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'array_key_exist...', '/Users/wenber/h...', 151, Array)
#1 /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php(151): array_key_exists('client', NULL)
#2 /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php(249): Illuminate\Support\Arr::exists(NULL, 'client')
#3 /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php(487): Illuminate\Support\Arr::forget(NULL, Array)
#4 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Listeners/FrameworkBootstrappedEvent/OverrideRedisManager.php(26): Illuminate\Support\Arr::pull(NULL, 'client', 'phpredis')
#5 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/ in /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 151

      +1 vendor frames
  2   [internal]:0
      Whoops\Run::handleShutdown()
[2020-06-17 16:59:16 *93905.1]	ERROR	php_swoole_server_rshutdown (ERRNO 503): Fatal error: Uncaught ErrorException: array_key_exists() expects parameter 2 to be array, null given in /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php:151
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'array_key_exist...', '/Users/wenber/h...', 151, Array)
#1 /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php(151): array_key_exists('client', NULL)
#2 /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php(249): Illuminate\Support\Arr::exists(NULL, 'client')
#3 /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php(487): Illuminate\Support\Arr::forget(NULL, Array)
#4 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Listeners/FrameworkBootstrappedEvent/OverrideRedisManager.php(26): Illuminate\Support\Arr::pull(NULL, 'client', 'phpredis')
#5 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/ in /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 151
[2020-06-17 16:59:16 $93857.0]	WARNING	swManager_check_exit_status: worker#6[pid=93901] abnormal exit, status=255, signal=0
[2020-06-17 16:59:16 $93857.0]	WARNING	swManager_check_exit_status: worker#5[pid=93900] abnormal exit, status=255, signal=0
[2020-06-17 16:59:16 $93857.0]	WARNING	swManager_check_exit_status: worker#7[pid=93899] abnormal exit, status=255, signal=0
[2020-06-17 16:59:16 $93857.0]	WARNING	swManager_check_exit_status: worker#4[pid=93904] abnormal exit, status=255, signal=0
[2020-06-17 16:59:16 $93857.0]	WARNING	swManager_check_exit_status: worker#2[pid=93903] abnormal exit, status=255, signal=0

   Symfony\Component\ErrorHandler\Error\FatalError

  Uncaught ErrorException: array_key_exists() expects parameter 2 to be array, null given in /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php:151
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'array_key_exist...', '/Users/wenber/h...', 151, Array)
#1 /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php(151): array_key_exists('client', NULL)
#2 /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php(249): Illuminate\Support\Arr::exists(NULL, 'client')
#3 /Users/wenber/htdocs/work/socialab/vendor/laravel/framework/src/Illuminate/Support/Arr.php(487): Illuminate\Support\Arr::forget(NULL, Array)
#4 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Listeners/FrameworkBootstrappedEvent/OverrideRedisManager.php(26): Illuminate\Support\Arr::pull(NULL, 'client', 'phpredis')
#5 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/

  at vendor/laravel/framework/src/Illuminate/Support/Arr.php:151
    147|         if ($array instanceof ArrayAccess) {
    148|             return $array->offsetExists($key);
    149|         }
    150|
  > 151|         return array_key_exists($key, $array);
    152|     }
    153|
    154|     /**
    155|      * Return the first element in an array passing a given truth test.

**Comment by huang-yi** [comment]
这里确实有个小BUG，谢谢反馈。
