### ISSUE TITLE
RedisManager constructor arguments error

### ISSUE THREAD

**Issue by Johnzero** [huang-yi/shadowfax#17]
Uncaught TypeError: Argument 2 passed to Illuminate\Redis\RedisManager::__construct() must be of the type array, string given, called in /Users/wangsong/hyperf-skeleton/backend/vendor/huang-yi/shadowfax/src/Laravel/RedisManager.php on line 22 and defined in /U  
  sers/wangsong/hyperf-skeleton/backend/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php:41

**Comment by huang-yi** [comment]
请问Laravel的版本号是什么？

**Comment by huang-yi** [comment]
是个Laravel版本的兼容性BUG，谢谢反馈！

Laravel5.6及以前的版本，RedisManager的constructor只有两个参数
