### ISSUE TITLE
supervisor stop doesn't kill process

### ISSUE THREAD

**Issue by Hanson** [huang-yi/shadowfax#23]
![image](https://user-images.githubusercontent.com/10583423/85529708-edf9fe00-b63f-11ea-9ac4-1d436495b57b.png)

![image](https://user-images.githubusercontent.com/10583423/85529960-239ee700-b640-11ea-8b78-a10c196bfca9.png)

**Comment by Hanson** [comment]
fixed by put two new parameters into config belongs to your process with <your_process> name

```
stopasgroup=true
stopsignal=QUIT
```

see https://github.com/Supervisor/supervisor/issues/600

**Comment by huang-yi** [comment]
我平时使用的配置也没有加`stopasgroup=true`和`stopsignal=QUIT`，在用supervisorctl stop时好像没有遇到你这种情况，不知道是不是supervisor版本问题。

**Comment by Hanson** [comment]
@huang-yi 我之前也没有试过，直到我发现代码没有热更新，关闭了服务还能访问，一看进程就发现有非常多个在执行了，也没有报端口冲突
