### ISSUE TITLE
控制器里面怎么才能拿到webscoket

### ISSUE THREAD

**Issue by PrinceH** [huang-yi/shadowfax#34]
我想在控制器里发送数据

**Comment by huang-yi** [comment]
如果你是想在HTTP的控制器里给WebSocket客户端推送消息，只需要知道客户端的fd就行：

```php
if (shadowfax('server')->isEstablished($fd)) {
    shadowfax('server')->push($fd, $data);
}
```

上述`shadowfax('server')`获取的就是`Swoole\Server`实例。

**Comment by PrinceH** [comment]
> 如果你是想在HTTP的控制器里给WebSocket客户端推送消息，只需要知道客户端的fd就行：
> 
> ```
> if (shadowfax('server')->isEstablished($fd)) {
>     shadowfax('server')->push($fd, $data);
> }
> ```
> 
> 上述`shadowfax('server')`获取的就是`Swoole\Server`实例。

确实我想的是这样 但是通过http推送有时候不生效isEstablished总是为false

**Comment by huang-yi** [comment]
isEstablished返回false，是不是客户端确实已经和服务端断开连接了呢？还有，一定要确保fd是websocket客户端的。

**Comment by PrinceH** [comment]
> isEstablished返回false，是不是客户端确实已经和服务端断开连接了呢？还有，一定要确保fd是websocket客户端的。

没有断开连接前端是能send数据给服务器的 但是服务器通过http推送有很大几率isEstablished为false fd也是正确的

**Comment by PrinceH** [comment]
> isEstablished返回false，是不是客户端确实已经和服务端断开连接了呢？还有，一定要确保fd是websocket客户端的。

貌似mode为base会出现这种情况process并不会

**Comment by huang-yi** [comment]
这种情况只能去Swoole社区找找答案了。

不过我个人建议websocket服务器还是尽量使用process模式，Swoole的base模式相比于process模式，会有一些特性上的缺失。

**Comment by PrinceH** [comment]
> 这种情况只能去Swoole社区找找答案了。
> 
> 不过我个人建议websocket服务器还是尽量使用process模式，Swoole的base模式相比于process模式，会有一些特性上的缺失。

好的好的 谢谢啦~

**Comment by PrinceH** [comment]
不过要是把http服务器弄成websocket服务器 协程就开不了了 这个我自己也不是很清楚 刚刚接触swoole

**Comment by huang-yi** [comment]
websocket服务器也可以开启协程啊，并且也不影响原来的http服务器。你说的“开不了协程”是指哪方面的问题呢？有没有具体的错误？

**Comment by PrinceH** [comment]
> websocket服务器也可以开启协程啊，并且也不影响原来的http服务器。你说的“开不了协程”是指哪方面的问题呢？有没有具体的错误？

![image](https://user-images.githubusercontent.com/33449867/88457583-4f6cf100-ceba-11ea-97b1-c624bdca9385.png)

![image](https://user-images.githubusercontent.com/33449867/88457593-627fc100-ceba-11ea-876e-f3bf68ef49b2.png)

**Comment by huang-yi** [comment]
的确WebSocket服务开启协程时会有问题，我新建了一个issue（#37）是关于这个BUG的。感谢你的反馈。

**Comment by wenber-yu** [comment]
如何在控制器串获取对应$fd呢? 
在Websocket/Handler/EchoServer中的onMessage中如果获取$request->user呢?

**Comment by huang-yi** [comment]
@wilbur-oo websocket和http的生命周期不一样，request对象在handshake阶段就被释放掉了，所以用户和fd的关系映射需要自行实现
