### ISSUE TITLE
非协程模式下Facade调用问题

### ISSUE THREAD

**Issue by Huangjunm** [huang-yi/shadowfax#35]
我参考适配器的代码，加了TymonJwtAuthCleaner；并且在配置中的abstracts加了以下配置：
- tymon.jwt
- tymon.jwt.auth
- tymon.jwt.provider.jwt
- tymon.jwt.provider.jwt.namshi
- tymon.jwt.provider.jwt.lcobucci
- tymon.jwt.provider.auth
- tymon.jwt.provider.storage
- tymon.jwt.manager
- tymon.jwt.blacklist
- tymon.jwt.payload.factory
- tymon.jwt.validators.payload

启动服务之后，使用不同用户token获得的用户信息还是同一个。

**Comment by huang-yi** [comment]
这个Cleaner我又测试了一遍应该没问题啊。只要路由设置了jwt的auth中间件，且token传对了，auth()->user()就能获取到对应的用户。

不知道你代码里面是怎么获取登录用户的，如果是使用`auth()->user()`应该没问题的。不知道你的代码里面有没有其他操作？

**Comment by Huangjunm** [comment]
我定义了两个guard(auth.php下)。分别是`game`和`admin`。
![image](https://user-images.githubusercontent.com/10103989/88357713-d5941500-cd9e-11ea-8f19-d3ee661e5967.png)

中间件里面设置了`auth:game`，然后在控制器中用`Illuminate\Support\Facades\Auth::user()`获取。

然后用不同的用户token去获取用户，第二次得到的用户是第一个的用户信息（已经确认是不同用户的token），且确认了cleaner有执行，配置的abstracts有rebind。不知道为啥...

**Comment by Huangjunm** [comment]
用auth()->user（） 这个可以。。`Illuminate\Support\Facades\Auth::user()`用这个方法不行。
这个能怎么改吗？

**Comment by huang-yi** [comment]
Facade在非协程模式下确实有个BUG，忘记了清理Facade里面缓存的实例。

感谢反馈，我将在下个小版本将修复这个 BUG
