### ISSUE TITLE
提问 支持Laravel那些版本?

### ISSUE THREAD

**Issue by cexll** [huang-yi/shadowfax#43]
我用的Laravel6 但是使用过程发现,提升并不明显

**Comment by huang-yi** [comment]
支持Laravel5.5以上的版本。一般可以从`composer.json`里面看版本依赖。

关于提升不明显，这个我很难帮你找原因。主要和你的代码有关系，不是说用了这个拓展包就能帮你提升性能的。

**Comment by cexll** [comment]
谢谢回答
