### ISSUE TITLE
[bug]Websocket connect ? worker_num

### ISSUE THREAD

**Issue by cexll** [huang-yi/shadowfax#44]
启用Websocket worker_num为1 ， 创建一个websocket链接， 第二个就无法链接， 
worker_num = 8 ， 则连接8人之后， 就无法继续链接， 
不清楚是bug还是机制，我认为应该是bug

**Comment by huang-yi** [comment]
这里有个线上的例子：[https://websocket.huangyi.tech/chatroom](https://websocket.huangyi.tech/chatroom)，是使用Shadowfax搭建的websocket服务，只开了1个worker进程，应该是可以同时建立连接很多连接的，你可以打开多个浏览器tab测试一下。

要不你把你的`shadowfax.yml`和Handler代码贴出来看一下吧，我帮忙排查一下是不是其他什么问题。

**Comment by cexll** [comment]
谢谢回答， 我之前测试在公司VMware（Ubuntu20LTS） 我今天在家用WSL2 测试一下， 如果还是那个问题，我在给你发一下

**Comment by cexll** [comment]
在WSL2 ， 1worker进程， 可以多用户连接， 应该是我的操作问题， 我把代码留着周一在继续试试， 打扰了， shadowfax good
