### ISSUE TITLE
执行 php shadowfax reload，并没有重新加载 helper.php 文件。

### ISSUE THREAD

**Issue by dafa168** [huang-yi/shadowfax#60]
在 bootstrap/helper.php（通过composer加载） 文件中增加了函数， 执行php shadowfax reload后， 发现控制器中还是调用不到 函数？ 直接报错  call undefined function xxx ?

**Comment by huang-yi** [comment]
的确是这样的。如果你了解过composer的原理就很清楚原因了，class文件都是通过`spl_autoload_register`来延迟加载的，而普通的file是在程序最开始处被require进来的，意味着是在swoole的master进程内进行的，所以无法达到重载的效果。

如果你的`bootstrap/helper.php`需要重载，可以改成在`bootstrap/app.php`中手动require，这样能保证你的文件是在swoole的worker进程中被require的。

**Comment by dafa168** [comment]
明白了。 谢谢
