### ISSUE TITLE
shadowfax性能耗费太高  是否有什么优化办法

### ISSUE THREAD

**Issue by johnmai-dev** [huang-yi/shadowfax#61]
![image](https://user-images.githubusercontent.com/1825679/103205639-f60b6100-4934-11eb-8c26-1abe3eeabd05.png)
现在链接量不多  才1千多  理论上1千多链接不应该靠不住

![image](https://user-images.githubusercontent.com/1825679/103205707-2521d280-4935-11eb-9c52-9ec0fce457b8.png)

**Comment by johnmai-dev** [comment]
@huang-yi

**Comment by johnmai-dev** [comment]
重启shadowfax之后  cpu占用瞬间降下来

**Comment by johnmai-dev** [comment]
感觉内存一直往上升  不降下来

**Comment by huang-yi** [comment]
如果内存占用高，很有可能是代码里面有内存泄漏的情况，需要仔细排查一下。我自己很多项目都是用shadowfax跑的，有些几个月都没重启过了，内存使用情况一直都正常。

之前听说swoole tracker有免费版的，你可以尝试一下，虽然我也没用过🤣

**Comment by johnmai-dev** [comment]
我直接复用你ChatroomServer那里面的示例了 
 `    protected function bind(Connection $connection, Request $request): void
    {
        $user = Auth::user();
        if (empty($user)) {
            $this->log('bind unauthenticate user', 'error');
            return ;
        }
        $clientInfo = [
            'id'        => $user->id,
            'nickname'  => $user->nickname
        ];
        $this->clients[$connection] = $clientInfo;


        $this->redisClient->sadd(‘test’, $user->id);
        $currentCount = $this->redisClient->scard(‘test’);
        $this->redisClient->hset('users', $user->id, json_encode($clientInfo));
    }`


其次就是onClose 加了 ` // 处理用户离线时间
        if ($userInfo && is_array($userInfo)) {
            event(new UserOffline($userInfo, now()));
        }`

会不会是这个new UserOffline没有销毁

**Comment by johnmai-dev** [comment]
我把new UserOffline unset了  内存依然是泄漏的   不会是因为redis   看别人说swoole跟redis是会存在内存泄漏

**Comment by johnmai-dev** [comment]
在shadowfax里面如何使用onWorkerStop onWorkerStart？

**Comment by huang-yi** [comment]
源码的`src/Events`文件夹下面有swoole的各个生命周期事件，可以这样注入自定义回调：

首先创建listener：
```php
<?php
namespace App\Listeners;

use HuangYi\Shadowfax\Events\WorkerStartEvent;

class FooListener
{
    /**
     * Handle the event.
     *
     * @param  \HuangYi\Shadowfax\Events\WorkerStartEvent  $event
     * @return void
     */
    public function handle(WorkerStartEvent $event)
    {
        // do something...
    }
}
```

然后在`bootstrap/shadowfax.php`中监听事件：
```php
use App\Listeners\FooListener;
use HuangYi\Shadowfax\Events\WorkerStartEvent;

shadowfax('events')->listen(WorkerStartEvent::class, new FooListener);
```
