### ISSUE TITLE
提示 too many attempts

### ISSUE THREAD

**Issue by ouyangfangyuan** [huang-yi/shadowfax#62]
1.我对接口请求次数加了限制,在shadowfax启动后,会提示too many attempts

**Comment by huang-yi** [comment]
文档里面有说明哦：

请务必将Shadowfax监听的IP（默认为127.0.0.1）填加到`App\Http\Middleware\TrustProxies`中去，这样才能在你的Laravel程序中获取到正确的IP、域名等。
