### ISSUE TITLE
post 响应状态码 204

### ISSUE THREAD

**Issue by yiqun** [huang-yi/shadowfax#63]
作者你好！鄙人现在遇到一个问题，在使用 shadowfax 的端口直接提供服务时，通过浏览器发送 post 请求，会返回 204 状态码（OPTIONS），也没有返回任何内容；但是使用 nginx 转发给 shadowfax 服务，则可以返回 200 状态码和内容。

我在相应的业务代码写了日志，当请求 post 到 shadowfax 的服务端口时，能够完整记录整个执行的过程，但就是没有输出。

系统：alpine 3.12
php: 7.3.27
swoole: 4.6.4-dev
shadowfax: ^2.10

客户端和服务器的域名地址不一样，可能是跨域的问题？如果是，请教一下如何处理？

**Comment by huang-yi** [comment]
从你的描述来看，应该是跨域问题，如果你是最新版的Laravel可以参考[官方文档](https://laravel.com/docs/8.x/routing#cors)处理

**Comment by yiqun** [comment]
@huang-yi 谢谢答复！

实在抱歉，是我们业务代码有问题，响应的 header 有一个 " content-type" 的属性，这个属性前面多了一个空格，导致浏览器判断为非法 header 而报错。很奇怪的是 nginx 会纠正这种不规范的 header 。
