### ISSUE TITLE
[Document Request] Do you have time to make a comparison to laravel octane?

### ISSUE THREAD

**Issue by diyism** [huang-yi/shadowfax#64]
I knew that shadowfax have done many optimizations to laravel on swoole, but I haven't seen similar introductions about laravel octane, do you have time to make a comparison between shadowfax and laravel octane to show the advantage of shadowfax?
ref: https://github.com/laravel/octane

**Comment by diyism** [comment]
Currently "laravel octane" doesn't support connection pool, shadowfax is still best: https://github.com/laravel/octane/issues/223

**Comment by huang-yi** [comment]
Octane毕竟是官方维护的，生态圈内的其他packages都会主动去适配Octane解决内存泄漏问题。你提问的协程适配只是时间问题，所以支持官方的package没毛病 ☕️
